config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/home' => 'home#index'

  resources :establishments do
    resources :reviews
  end
  # get '/establishments' => 'establishments#index'
  # get '/establishments/:id' => 'establishments#show'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password

  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  validates :username, presence: true, uniqueness: true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(identifier, password)
        user = User.find_by("#{identifier.include?('@') ? 'email' : 'username'} = ?", identifier)
        (user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)) ? user : nil
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize(auth_type, creator = nil)
    (creator.nil?) ? send(auth_type) : send(auth_type, creator)
  end


  private
  def user
    unless is_user?
      flash[:alert] = "You aren't authorized to visit that page. Please sign in or register an account with us."
      redirect_to '/'
    end
  end

  def admin
    unless is_user? && is_admin?
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end

  def is_user?
    !current_user.nil?
  end
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController

  def index
    if params[:kids]
      response = HTTParty.get("http://localhost:3000/establishments?query=#{params[:kids]}", format: :plain)
      @establishments = JSON.parse response, symbolize_names: true
      render :index
    elsif params[:indoor]
      response = HTTParty.get("http://localhost:3000/establishments?query=#{params[:indoor]}", format: :plain)
      @establishments = JSON.parse response, symbolize_names: true
      render :index
    elsif params[:search]
      response = HTTParty.get("http://localhost:3000/establishments?query=#{params[:search]}", format: :plain)
      @establishments = JSON.parse response, symbolize_names: true
      render :index
    else
      response = HTTParty.get("http://localhost:3000/establishments", format: :plain)
      @establishments = JSON.parse response, symbolize_names: true
      render :index
    end
  end

  def show
    id = params[:id]
    response = HTTParty.get("http://localhost:3000/establishments/#{id}", format: :plain)
    @establishment = JSON.parse response, symbolize_names: true

    response2 = HTTParty.get("http://localhost:3000/establishments/#{id}/reviews", format: :plain)
    @reviews = JSON.parse response2, symbolize_names: true
    render :show
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    render :index
  end

end

app/controllers/just_another_controller.rb
class JustAnotherController < ApplicationController
  before_action :authorize, only: [:secret]

  def secret
  end

end

app/controllers/reviews.controller.rb
class ReviewsController < ApplicationController

  before_action only: [:edit, :update, :destroy] do
          authorize(:admin)
      end
      before_action only: [:new, :show] do
              authorize(:user)
          end
  def new
    id = params[:id]
    HTTParty.post("http://localhost:3000/establishments/#{id}/reviews", format: :plain)

    render :new
  end

  def create
    @establishment = Establishment.find(params[:establishment_id])
    @review = @establishment.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to establishment_path(@establishment)
    else
      render :new
    end
  end

  # def show
  #   @product = Product.find(params[:product_id])
  #   @review = Review.find(params[:id])
  #   render :show
  # end
  #
  # def edit
  #   @product = Product.find(params[:product_id])
  #   @review = Review.find(params[:id])
  #   render :edit
  # end
  #
  # def update
  #   @review = Review.find(params[:id])
  #   if @review.update(review_params)
  #     redirect_to product_path(@review.product)
  #   else
  #     render :edit
  #   end
  # end
  #
  # def destroy
  #   @review = Review.find(params[:id])
  #   @review.destroy
  #   redirect_to product_path(@review.product)
  # end

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/establishments"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Woof! You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "Ruh-roh! There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/establishments/index.html.erb
<div id="map"></div>
<div class="container-fluid">
  <script>

    var dogIcon = L.icon({
      iconUrl: '<%= asset_path "dog-solid.svg" %>',
      iconSize: [30, 30], // size of the icon
      iconAnchor: [0, 0], // point of the icon which will correspond to marker's location
      popupAnchor: [0, 0] // point from which the popup should open relative to the iconAnchor
    });

    // initialize the map
    var map = L.map("map").setView([45.520656, -122.677388], 13);

    // load a tile layer
    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
    {
      attribution: 'Tiles by a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
      maxZoom: 17,
      minZoom: 9
    }).addTo(map);

    if (marker) {

    } else {
      let marker;
    }

  </script>
  <h1>Watering Holes</h1>
  <div id="search-criteria" class="container">
    <form action='/establishments' class="form-inline my-2 my-lg-0">
      <input name="search" class="form-control mr-sm-2" type="search" placeholder="Search">
      <button class="btn btn-primary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
    <form action='/establishments' class="form-inline my-2 my-lg-0">
    <button class="btn btn-info my-2 my-sm-0" type="submit" name="indoor_access">Indoor Access</button>
    <button class="btn btn-info my-2 my-sm-0" type="submit" name="kid_friendly">Kid-Friendly</button>
    <button class="btn btn-info my-2 my-sm-0" type="submit" name="serves_food">Serves Food</button>
    <a><%= link_to "Remove Filters", establishments_path, role: "button", class: "btn btn-outline-info" %></a>
    </form>
  </div>
  <div class="container">
    <center><p>There are <%= @establishments.count %> watering holes.</p></center>
    <div class="scroll-box">
      <% if @establishments %>
      <% @establishments.each do |establishment| %>
      <p><%= link_to establishment.fetch(:name), "/establishments/#{ establishment.fetch(:id) }", class: "text-white" %></p>
      <script>
        marker = L.marker([<%= establishment.fetch(:lat) %>, <%= establishment.fetch(:long) %>], {icon: dogIcon}).addTo(map);
        marker.bindPopup('<%= link_to establishment.fetch(:name), "/establishments/#{ establishment.fetch(:id) }" %>').closePopup();
      </script>
      <% end %>
    </div>
    <center><p class="note">Scroll down to view the complete list.</p></center>
    <center><i class="fas fa-arrow-circle-down"></i></center>
  </div>
  <% else %>
  <p>Ruh roh! There are currently no dog-friendly watering holes that meet your search criteria.</p>
  <% end %>
</div>

app/views/establishments/show.html.erb
<div class="container-fluid">
  <h2><%= @establishment.fetch(:name) %></h2>
  <div class="social-icons">
    <center>
      <h3><a href="<%= @establishment.fetch(:website) %>"><i class="fas fa-globe"></i></a> <i class="fab fa-instagram"></i> <i class="fab fa-facebook"></i></h3>
    </center>
  </div>
  <div class="container">
    <hr>
    <div class="image-gallery">
      <img class="insta" src="<%= @establishment.fetch(:img) %>" alt="Instagram" height="224" width="224">
      <img class="insta" src="<%= @establishment.fetch(:img2) %>" alt="Instagram" height="224" width="224">
      <img class="insta" src="<%= @establishment.fetch(:img3) %>" alt="Instagram" height="224" width="224">
      <img class="insta" src="<%= @establishment.fetch(:img4) %>" alt="Instagram" height="224" width="224">
    </div>
    <div class="row">
      <div class="col">
        <h3>Information</h3>
        <br>
        <h6><i class="fas fa-question-circle text-info"></i> Where is it located?</h6>
        <p><%= @establishment.fetch(:neighborhood) %>; <%= @establishment.fetch(:address) %></p>
        <h6><i class="fas fa-question-circle text-info"></i> Is there food?</h6>
        <% if @establishment.fetch(:food) != "None" %>
        <p>Yes, food options inlcude: <%= @establishment.fetch(:food) %></p>
        <% else %>
        <p>No</p>
        <% end %>
        <h6><i class="fas fa-question-circle text-info"></i> Is it kid-friendly?</h6>
        <% if @establishment.fetch(:kid_friendly) == true %>
        <p>Yes</p>
        <% else %>
        <p>No</p>
        <% end %>
        <h6><i class="fas fa-question-circle text-info"></i> Are dogs allowed inside?</h6>
        <% if @establishment.fetch(:restrictions) == "None" %>
        <p>Yes</p>
        <% else %>
        <p>No, dogs are only allowed on the patio.</p>
        <% end %>
      </div>
      <div class="col">
        <h3>Reviews</h3>
        <br>
        <% if @reviews %>
        <% @reviews.each do |review| %>
        <% review.fetch(:rating).to_i.times do  %>
        <i class="fas fa-star text-warning"></i>
        <% end %>
        from <%= review.fetch(:author) %>
        <p>"<%= review.fetch(:content_body) %>"</p>
        <% end %>
        <% else %>
        <p>There are no reviews.</p>
        <% end %>
        <% if current_user %>
        <p><%= link_to "Write a Review", "/establishments/reviews/new", class: "text-white" %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid">
  <center><img src="/assets/bone-beer-solid-white.svg" width="60" height="60" alt="logo"></center>
  <div class="container">
    <hr>
  </div>
  <h1 id="clipped-title">Hops & Hounds</h1>
  <center><h3>Find the <em>pawfect</em> pint for you and your pup!</h3></center>
  <div class="enter">
    <%= link_to "Must be 21+ to enter", "/establishments", class: "btn btn-danger btn-lg text-white" %>
  </div>
  <center><p class="note">By clicking the button above, you agree that you are at least 21 years old.</p></center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hops & Hounds</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css"/>
  <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/415ba7a6f3.js" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">
      <img src="/assets/bone-beer-solid-classic-blue.svg" width="30" height="30" class="d-inline-block align-top" alt="logo">
      Hops & Hounds
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="/establishments">Click here for a list of local watering holes!</a>
        </li>
      </ul>
      <% if current_user %>
      <span class="text-dark">Cheers, <strong><%= current_user.username %></strong>!</span> <%= link_to "Sign out", "/signout", class: "nav-link" %>
      <% else %>
      <%= link_to "Sign up", "/signup", class: "nav-link" %> <%= link_to "Sign in", "/signin", class: "nav-link" %>
      <% end %>
    </div>
  </nav>
  <%= yield %>
</body>
</html>

app/views/reviews/new.html.erb
<div class="container-fluid">

</div>

app/views/users/new.html.erb
<div class="container-fluid">
  <h2>Sign up</h2>
  <div class="container">
    <hr>
  </div>
  <div class="user-forms">
    <div class="form-group">
      <%= form_for @user do |f| %>
    <h4>  <%= f.label "User Name" %>
      <%= f.text_field :username %>
      <%= f.label "Email" %>
      <%= f.text_field :email %> </h4>
    <h4><%= f.label "Password" %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "Sign Up", class: "btn btn-primary" %></h4>
      <% end %>
    </div>
  </div>
</div>